
mkdir custom_jwt && touch custom_jwt/__init__.py && touch custom_jwt/custom_jwt.py

docker build . -t timelime-backend-img
docker run -p 5000:5000 -e GOOGLE_APPLICATION_CREDENTIALS=secrets/timelime-dev-sa.json timelime-backend-img
gcloud run deploy timelime-backend --region=europe-west2 --source . --port 5000 --no-allow-unauthenticated

gcloud endpoints services deploy openapi-run.yaml --project timelime-dev


gcloud config get-value account
gcloud config set account main-641@timelime-dev.iam.gserviceaccount.com
gcloud auth print-identity-token main-641@timelime-dev.iam.gserviceaccount.com
gcloud auth print-identity-token xxxx@xxx.iam.gserviceaccount.com

curl --request GET https://gateway-uavkhjofda-nw.a.run.app/quentinoo --header "Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjYzODBlZjEyZjk1ZjkxNmNhZDdhNGNlMzg4ZDJjMmMzYzIzMDJmZGUiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiUXVlbnRpbiBEdXZlcmfDqSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQWNIVHRkR1pyN1VqVGdDUFJOUmhISGV5TGFLOXhTUzJPREZXQTQwQW5fMmNJQmI3N0U9czk2LWMiLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGltZWxpbWUtZGV2IiwiYXVkIjoidGltZWxpbWUtZGV2IiwiYXV0aF90aW1lIjoxNjkyMDA1Mzg2LCJ1c2VyX2lkIjoiMTJ6RmljUnRueVNlSDMyRE9jRFJvR1FpeVB2MSIsInN1YiI6IjEyekZpY1J0bnlTZUgzMkRPY0RSb0dRaXlQdjEiLCJpYXQiOjE2OTIwMDUzODYsImV4cCI6MTY5MjAwODk4NiwiZW1haWwiOiJxdWVudGluLmR1dmVyZ2VAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZ29vZ2xlLmNvbSI6WyIxMDYzMTA2NDU4NzEyNDMyNDkzMDUiXSwiZW1haWwiOlsicXVlbnRpbi5kdXZlcmdlQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6Imdvb2dsZS5jb20ifX0.Qvmvi3gIDNpiCGcR83_-Kuez8M7bUoSZQHX72IdLFecv_5hW7fvFaS_T9WFg9pAQHaReuNQdLaMFBKX7VlnHqugd63aKcn5V_vgz2gnIGcFWQ7s5ak9CFfgrbuz2GFhPosjXc4qquyP3_g_2jqdFm6RPHqj4yDm9VHhy6VUWagJ-gapDS2qYVhQ2zm4nJ2g0WeebfYGvddH7977fr2Zp6Y8SDK-cBEo66NnUTm8C-RHED-mFm_UMb_bOZdeZHMMDffd_KucCWxsZyKgnC3OO8zz5PkO26J6JCMbYMoIFPgzNPVwMqm2x3JdqUiw-I8nvL2xlNCQZgwGOHsDWpgiP-Q"


curl --request DELETE http://localhost:5000/event/gNIghD3O4TS9IURlZPlB --header "Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjYzODBlZjEyZjk1ZjkxNmNhZDdhNGNlMzg4ZDJjMmMzYzIzMDJmZGUiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiUXVlbnRpbiBEdXZlcmdlIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FBY0hUdGZYTllJZ3ppbDhaQm1Kd3NEZHBoY1RPeVpYOEMza1JMNzdrY3JmU3A0RkR3PXM5Ni1jIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL3RpbWVsaW1lLWRldiIsImF1ZCI6InRpbWVsaW1lLWRldiIsImF1dGhfdGltZSI6MTY5MjcwODQ0NiwidXNlcl9pZCI6IlJoZXQ5QW5zbGhZYUxEZWYzb3Ayc2hrZ1NETTIiLCJzdWIiOiJSaGV0OUFuc2xoWWFMRGVmM29wMnNoa2dTRE0yIiwiaWF0IjoxNjkyNzA4NDQ2LCJleHAiOjE2OTI3MTIwNDYsImVtYWlsIjoicXVlbnRpbi5kdXZlcmdlQGVzc2VuY2VtZWRpYWNvbS5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJnb29nbGUuY29tIjpbIjExMDQzMDgwOTcyODg4NzAxOTA4NyJdLCJlbWFpbCI6WyJxdWVudGluLmR1dmVyZ2VAZXNzZW5jZW1lZGlhY29tLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6Imdvb2dsZS5jb20ifX0.Qfug45VbihqP1bGRfMYPRjRJDU_p6ZNz-sTicqQigF_ELhNF8vVZ4aVuUY3bo0RcF67TgOKMapz0jBYXvCxa6Cni0gZZmPNADV_4WUUS1vgURgrV-4cLbFeXdss1Jbt98NMymdPM3zBeCuXhkZSoXlCVO19KgkYG30Aao07R-cs-2M-MIuHonKToEeipKXIGsVHXxs0AhUgLC0sWw_1y7NNHYVlkUYCQQn-SM7vj9UcxuK-IKySLzkiY7XUS2Lg9cS8kogXulBAntNxyqtraUdPQEwz9C8JdYTdTjvnhOEUAcsXJc5uCCSd3GnrR68R95ZuBBJ6eS7in7YF0soFUYg"

curl --X POST -H "Content-Type: application/json" -d "{}" http://localhost:5000/unauthedTimeline

http://localhost:4200/timeline/3-mousquetaires-1EAy1aSxNKaQfLAXiSf9
http://localhost:4200/timeline/histoire-du-monde-5paHZVggDt2XSAxG2iDl

