swagger: '2.0'
info:
  title: Timelime API
  description: Timelime API
  version: 1.0.0
host: gateway-uavkhjofda-nw.a.run.app
schemes:
  - https
produces:
  - application/json

paths:
  /quentinoo:
    get:
      summary: Gtet Quientin
      operationId: add_update_employee
      responses:
       '200':
          description: OK
          schema:
            type: string
      x-google-backend:
        address: https://timelime-backend-uavkhjofda-nw.a.run.app/quentin
        protocol: h2
