name: Push to Dev

on:
  push:
    branches: [ dev ]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}

    - name: Build Docker image
      run: docker build . -t timelime-bakend-img

    - name: Tag Docker image
      run: docker tag timelime-bakend-img:latest europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/timelime-bakend/timelime-bakend-img:latest

    - name: Push image
      run: docker push europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/timelime-bakend/timelime-bakend-img:latest

    - name: Deploy to Cloud Run
      run: gcloud run deploy timelime-bakend --image europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/timelime-bakend/timelime-bakend-img:latest --region europe-west2 --no-allow-unauthenticated


    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 3.8

    # - name: Run Python script
    #   run: |
    #     python deploy-gateway.py

    # - name: Read generated ID from file
    #   id: read-id
    #   run: echo "GENERATED_ID=$(cat config-id.txt)" >> $GITHUB_ENV

    # - name: chmod
    #   run: chmod +x gcloud_build_image.sh

    # - name: Deploy ESPV2 image
    #   run: ./gcloud_build_image.sh -s gateway-uavkhjofda-nw.a.run.app -c ${{ env.GENERATED_ID }} -p timelime-dev

    # - name: Deploy ESPV2 service
    #   run: gcloud run deploy gateway --image="gcr.io/timelime-dev/endpoints-runtime-serverless:2.45.0-gateway-uavkhjofda-nw.a.run.app-${{ env.GENERATED_ID }}" --allow-unauthenticated --region europe-west2 --platform managed --project=timelime-dev