name: Push to Dev

on:
  push:
    branches: [ dev ]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Login
    #   uses: google-github-actions/setup-gcloud@v0
    #   with:
    #     project_id: ${{ secrets.GCP_PROJECT_ID }}
    #     service_account_email: ${{ secrets.GCP_EMAIL }}
    #     service_account_key: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run Python script
      run: |
        python deploy-gateway.py

    - name: Read generated ID from file
      id: read-id
      run: echo "GENERATED_ID=$(cat generated_id.txt)" >> $GITHUB_ENV

    - name: Use ID in another step
      run: echo "The generated ID is $GENERATED_ID"
